### ISSUE TITLE
Add source information to the JSON output

### ISSUE THREAD

**Issue by ESultanik** [trailofbits/polytracker#17]
The output should include the name of the input file from which the bytes originated. This will also future-proof the format for if/when PolyTracker enables tracking from multiple files (or sockets?) at once.
```json
{
  "dfs$ensure_solid_xref": {
    "input_bytes": {
      "POLYTRACK filename": [
        2276587,
        2276588
      ]
    }
  },
⋮
```

**Comment by ThatsNotVeryCashMoneyOfYou** [comment]
I'm going to implement this via repurposing our bitfield to keep track of what taint source its from. This will allow us to track 8 taint sources. If we see more than one bit flipped, we know its influenced from more than one taint source.

**Comment by ThatsNotVeryCashMoneyOfYou** [comment]
This might be a bit tricker to support multiple taint sources, i.e. right now our addressing schema is based around taint labels corresponding to offsets, this doesnt work well if we have multiple files.

**Comment by notBD** [comment]
This has been done since dec/jan
