### ISSUE TITLE
Prominently include license for nlohmann-json

### ISSUE THREAD

**Issue by bradlarsen** [trailofbits/polytracker#22]
We currently use (at least) `CRoaring` and `nlohmann-json` as third-party dependencies. These are released under the Apache v2 license and an MIT license, respectively.

We should make sure that we are distributing the third-party packages licenses, as required by them. Perhaps add a top-level `LICENSES.thirdparty` directory with license files there.

**Comment by ESultanik** [comment]
@ThatsNotVeryCashMoneyOfYou do we still use both of those? I thought you were thinking about abandoning `nlohmann-json` in favor of LLVM's internal JSON library.

**Comment by bradlarsen** [comment]
We are vendoring both of those dependencies now (including the source within our tree).

I made an attempt to switching to LLVM's JSON library, but that had the unfortunate side-effect of requiring that `libLLVMSupport` be linked into every polytracker-instrumented binary. So to avoid that, I decided to stick with the header-only nlohmann-json library we were already using.

**Comment by bradlarsen** [comment]
Note, we also use the `lrucache` library from lamerman: https://github.com/lamerman/cpp-lru-cache

**Comment by carsonharmon** [comment]
Update: We no longer use CRoaring, and we can remove nlohmann, and we removed the LRU cache.
