### ISSUE TITLE
Mutexes aren't used consistently in the polytracker runtime implementation in `dfsan.cc`

### ISSUE THREAD

**Issue by bradlarsen** [trailofbits/polytracker#25]
In particular, look for the uses of `function_to_bytes` and `union_table` within `polytracker/dfsan/dfsan_rt/dfsan/dfsan.cc`. Each of these variables has an accompanying `std::mutex`, but the mutex is not taken everywhere the variables are touched.

Additionally, it would be more robust to use `std::lock_guard<std::mutex>` or `std::unique_lock<std::mutex>` instead of manually calling `.lock()` and `.unlock()` on the mutex variables.

**Comment by notBD** [comment]
Can you explain what lock_guard and unique_lock do? Note that i have refactored everything so that we have a single mono lock, which while not performant it does the job

**Comment by bradlarsen** [comment]
`std::lock_guard<std::mutex>` is an RAII-style class.  You allocate a named one of those objects on the stack, passing the lock you want to hold to its constructor.  That acquires the lock.  When the named `std::lock_guard` object goes out of scope, its destructor releases the lock.  This kind of pattern ensures that the lock always gets released, even in the case of an early return, a thrown exception, etc.

`std::unique_lock<std::mutex>` is a newer API (?) that does more or less the same thing, but seems more complicated.

**Comment by bradlarsen** [comment]
P.S. the single lock design you mention sounds very reasonable if you want to actually have a hope of getting multithreaded code right :)

**Comment by carsonharmon** [comment]
Hey thats a very clean design (might refactor to that)! Threaded code seems to have been working for awhile now, so I'm closing this!
