### ISSUE TITLE
Change entry/exit instrumentation logic

### ISSUE THREAD

**Issue by carsonharmon** [trailofbits/polytracker#48]
There is a bug where functions that we don't want to instrument, like pthread_equal, even if specified in the abilist to ignore, do not have their prefix altered but are tagged with entry/exit instrumentations. 

To fix, we should change the way we track functions at runtime in the instrumentation. 

If a function is marked as uninstrumented, we do not log at runtime. So we can have that be a guard.

**Comment by notBD** [comment]
Right just a follow up - the logic in the dfsan pass was weird and not intuitive to me, it basically says "Don't instrument this function if it's discarded OR another flag related to it returning void/variable args etc". Even though we said to discard pthread, that specific function matched with the second criteria and became instrumented. 

In polytracker if you specify a function to be discarded it is now always ignored by instrumentation.

**Comment by carsonharmon** [comment]
Right, I think that this was changed now. This was due to the weird behavior with discard/custom/etc.  this is the code snippet now 

```
DataFlowSanitizer::WrapperKind DataFlowSanitizer::getWrapperKind(Function *F) {
  if (ABIList.isIn(*F, "custom"))
    return WK_Custom;
  if (ABIList.isIn(*F, "functional"))
    return WK_Functional;
  if (ABIList.isIn(*F, "discard"))
    return WK_Discard;

  return WK_Warning;
}
```

If we mark it as custom, always use the custom implementation if one exists. Same with functional. Discard is now last in the hierarchy, and WK_WARNING means nothing is good here.
