### ISSUE TITLE
Artifact data doesn't dump unless program exits normally

### ISSUE THREAD

**Issue by stevenagy** [trailofbits/polytracker#6341]
Hey all :),

I noticed that PolyTracker doesn't save its data unless the instrumented program exits without error. Carson suggested this is most likely due to the instrumentation relying on an `atexit` call and probably fixable with a signal handler. I'd be happy to provide any sample test cases if that helps!

All the best,
-Stefan

**Comment by ESultanik** [comment]
Our forthcoming major rewrite switches to emitting a SQLite database that gets populated dynamically at runtime.
